
USE Ecommerce;


DROP TABLE IF EXISTS Shipping;
DROP TABLE IF EXISTS Billing;
DROP TABLE IF EXISTS OrderDetails;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Cart;
DROP TABLE IF EXISTS Inventory;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Products;
